openapi: 3.0.1
info:
  title: Book Store API
  description: Simple API for an online book store.
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/orders:
    get:
      tags:
      - order-controller
      operationId: getAllBookOrders
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
      - order-controller
      operationId: createBookOrder
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/orders/order:
    post:
      tags:
      - order-controller
      operationId: createBookOrder_1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        author:
          type: string
        isbn:
          type: string
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        book:
          $ref: '#/components/schemas/Book'
